SELECT 
    P.*
FROM 
    PRODUCTS P
LEFT JOIN 
    ORDER_ITEMS OI 
        ON P.PRODUCT_ID = OI.PRODUCT_ID
LEFT JOIN 
    ORDERS O 
        ON OI.ORDER_ID = O.ORDER_ID
WHERE 
    O.STATUS != 'bought' 
    OR O.ORDER_ID IS NULL;